spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5435/news_app
    username: postgres
    password: postgres
    hikari:
      schema: news_app
      connection-timeout: 10000