spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/news_app
    username: postgres
    password: postgres
    hikari:
      schema: news_app
      connection-timeout: 10000
  flyway:
    installed-by: DaDenisov