version: '3'

services:
  postgres:
    image: postgres:12.19-alpine3.20
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news_app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
